version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@1
jobs:
  setup:
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          command: |
            export SKIP=$(git log -n 1 $CIRCLE_SHA1 --pretty=%B | grep -q "NOCIRCLECI" && echo "true" || echo "false")
            echo "{\"skip\": $SKIP}" >> set-up-params.json
      - continuation/continue:
          parameters: set-up-params.json
          configuration_path: .circleci/build.yml

workflows:
  configure:
    when:
      and:
        - matches:
            pattern: "^release.+"
            value: << pipeline.git.branch >>
    jobs:
      - setup
